[workspace]
members = ["pksc", "core", "macros"]
resolver = "2"

[workspace.package]
name = "packscript"
version = "0.1.0"
authors = ["ellipse12"]
description = "A universal package manager"
edition = "2021"
