[workspace]
members = ["pksc", "core", "macros"]
resolver = "2"

[workspace.package]
version = "0.1.2"
authors = ["ellipse12"]
description = "A universal package manager"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/hybal/packscript"
readme = "README.md"
