[package]
name = "macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
inventory = "0.3.17"
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full"] }
