= Syntax Overview
:hardbreaks:

This is an overview of the common syntax and functions that you can use in PackScript

== Variables

there are two kinds of variables, local and global. Local variables are declared with the `let` keyword and global variables with `set`.
[source, packscript]
----
let local = 1
set global = 2
----

there is also a difference in how you refer to these variables. Local variables are used normally without any differences, but to use a global variable you have to prefix it with `g:`
[source, packscript]
----
let local = 1

print local #nothing different

set global = "xyz"

print g:global #prefixed with g:
----

== Functions

Functions are basically everything in PackScript, since it is a functional language they are also values that can be passed around.

to create a function is similar to how you declare a variable, just with the addition of parameters before the equal sign (=)
[source, packscript]
----
let add (a,b) = a + b
----


== Shell Functions

[WARN]
You should only use shell functions when required, since commands are not cross-platform you cannot guarantee that it will work everywhere. Instead use the standard library functions as much as possible.

You can easily run any arbitrary shell function by just starting a line with a bang (!)
[source, packscript]
----
!echo "Hello, World!"
----

However, the process is not privileged by default (so on linux you can't use `sudo`). However you can ask for those permissions by adding another bang (!!). This will pause the script and ask the user for permission to elevate privileges. (this will likely change)
[source, packscript]
!!sudo apt update

[NOTE]
every bang-command uses the same process that is created on startup, if you need to create a new one see `exec`



